[2023-01-28T10:21:26.270736+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /Users/gabriel/TEST_SYMFONY/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-01-28T10:28:31.636351+00:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://127.0.0.1:8000/"" at /Users/gabriel/TEST_SYMFONY/vendor/symfony/http-kernel/EventListener/RouterListener.php line 128 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://127.0.0.1:8000/\" at /Users/gabriel/TEST_SYMFONY/vendor/symfony/http-kernel/EventListener/RouterListener.php:128)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /Users/gabriel/TEST_SYMFONY/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:185)"} []
[2023-01-28T10:28:31.771483+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"75b6f7"},"request_uri":"http://127.0.0.1:8000/_wdt/75b6f7","method":"GET"} []
[2023-02-02T08:26:05.745918+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-02-02T08:26:05.751006+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/gabriel/TEST_SYMFONY/config/routes/framework.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/Users/gabriel/Desktop/TEST_SYMFONY/vendor/symfony/config/Resource/FileResource.php","line":58,"trace":[{"file":"/Users/gabriel/Desktop/TEST_SYMFONY/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":44,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2023-02-02T08:26:05.819287+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-02-02T08:26:05.820646+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2023-02-02T08:26:05.906039+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"} {"params":{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"}} []
[2023-02-02T08:26:05.943612+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2023-02-02T08:26:06.182033+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f66ecd"},"request_uri":"http://127.0.0.1:8000/_wdt/f66ecd","method":"GET"} []
[2023-02-02T08:33:05.010352+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-02-02T08:33:05.012829+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2023-02-02T08:33:05.022586+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"} {"params":{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"}} []
[2023-02-02T08:33:05.025410+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2023-02-02T08:33:05.269481+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"95f725"},"request_uri":"http://127.0.0.1:8000/_wdt/95f725","method":"GET"} []
[2023-02-02T08:33:50.055466+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-02-02T08:33:50.056200+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2023-02-02T08:33:50.061909+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"} {"params":{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"}} []
[2023-02-02T08:33:50.064686+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2023-02-02T08:33:50.257221+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a01899"},"request_uri":"http://127.0.0.1:8000/_wdt/a01899","method":"GET"} []
[2023-02-02T08:38:02.275829+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-02-02T08:38:02.277592+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2023-02-02T08:38:02.283471+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"} {"params":{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"}} []
[2023-02-02T08:38:02.287234+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2023-02-02T08:38:02.454321+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"bda69d"},"request_uri":"http://127.0.0.1:8000/_wdt/bda69d","method":"GET"} []
[2023-02-02T08:42:45.662843+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-02-02T08:42:45.664889+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2023-02-02T08:42:45.673348+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"} {"params":{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"}} []
[2023-02-02T08:42:45.677449+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2023-02-02T08:42:45.853562+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"b328e5"},"request_uri":"http://127.0.0.1:8000/_wdt/b328e5","method":"GET"} []
[2023-02-02T08:42:46.309556+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-02-02T08:42:46.309983+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2023-02-02T08:42:46.314006+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"} {"params":{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"}} []
[2023-02-02T08:42:46.316057+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2023-02-02T08:42:46.502573+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"c2a936"},"request_uri":"http://127.0.0.1:8000/_wdt/c2a936","method":"GET"} []
[2023-02-02T10:11:41.756468+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\LoaderLoadException: "[Creation Error] An error occurred while instantiating the annotation @Route declared on method App\Controller\Admin\AdminPropertyController::edit(): "Unknown named parameter $methodes" in {"path":"..\/src\/Controller\/","namespace":"App\\Controller"} (which is being imported from "/Users/gabriel/Desktop/TEST_SYMFONY/config/routes.yaml"). Make sure there is a loader supporting the "attribute" type." at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/symfony/config/Loader/FileLoader.php line 178 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): [Creation Error] An error occurred while instantiating the annotation @Route declared on method App\\Controller\\Admin\\AdminPropertyController::edit(): \"Unknown named parameter $methodes\" in {\"path\":\"..\\/src\\/Controller\\/\",\"namespace\":\"App\\\\Controller\"} (which is being imported from \"/Users/gabriel/Desktop/TEST_SYMFONY/config/routes.yaml\"). Make sure there is a loader supporting the \"attribute\" type. at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/symfony/config/Loader/FileLoader.php:178)\n[previous exception] [object] (Doctrine\\Common\\Annotations\\AnnotationException(code: 0): [Creation Error] An error occurred while instantiating the annotation @Route declared on method App\\Controller\\Admin\\AdminPropertyController::edit(): \"Unknown named parameter $methodes\". at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:53)\n[previous exception] [object] (Error(code: 0): Unknown named parameter $methodes at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php:1472)"} []
[2023-02-02T10:12:28.734245+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-02-02T10:12:28.735225+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2023-02-02T10:12:28.741598+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"} {"params":{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"}} []
[2023-02-02T10:12:28.745648+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Users/gabriel/Desktop/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2023-02-02T10:12:28.916241+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"e7cff0"},"request_uri":"http://127.0.0.1:8000/_wdt/e7cff0","method":"GET"} []
[2023-02-02T13:29:37.553859+00:00] deprecation.INFO: User Deprecated: The "Monolog\Logger" class is considered final. It may change without further notice as of its next major version. You should not extend it from "Symfony\Bridge\Monolog\Logger". {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"Monolog\\Logger\" class is considered final. It may change without further notice as of its next major version. You should not extend it from \"Symfony\\Bridge\\Monolog\\Logger\". at /Applications/MAMP/htdocs/TEST_SYMFONY/vendor/symfony/error-handler/DebugClassLoader.php:337)"} []
[2023-02-02T13:29:37.556658+00:00] php.DEBUG: Warning: filemtime(): stat failed for /Users/gabriel/Desktop/TEST_SYMFONY/config/routes/framework.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/Applications/MAMP/htdocs/TEST_SYMFONY/vendor/symfony/config/Resource/FileResource.php","line":58,"trace":[{"file":"/Applications/MAMP/htdocs/TEST_SYMFONY/vendor/symfony/config/Resource/SelfCheckingResourceChecker.php","line":44,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2023-02-02T13:29:37.625653+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-02-02T13:29:37.626819+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2023-02-02T13:29:37.677409+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"} {"params":{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"}} []
[2023-02-02T13:29:37.696948+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /Applications/MAMP/htdocs/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Applications/MAMP/htdocs/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Applications/MAMP/htdocs/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Applications/MAMP/htdocs/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2023-02-02T13:29:37.872696+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"889276"},"request_uri":"http://127.0.0.1:8000/_wdt/889276","method":"GET"} []
[2023-02-02T13:31:21.780059+00:00] request.INFO: Matched route "home". {"route":"home","route_parameters":{"_route":"home","_controller":"App\\Controller\\HomeController::index"},"request_uri":"http://127.0.0.1:8000/","method":"GET"} []
[2023-02-02T13:31:21.793740+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":0} []
[2023-02-02T13:31:21.936480+00:00] doctrine.INFO: Connecting with parameters array{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"} {"params":{"url":"<redacted>","driver":"pdo_pgsql","host":"127.0.0.1","port":5432,"user":"app","password":"<redacted>","driverOptions":[],"defaultTableOptions":[],"dbname":"app","serverVersion":"15","charset":"utf8"}} []
[2023-02-02T13:31:21.966765+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at "127.0.0.1", port 5432 failed: Connection refused 	Is the server running on that host and accepting TCP/IP connections?" at /Applications/MAMP/htdocs/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php line 77 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 7): An exception occurred in the driver: SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Applications/MAMP/htdocs/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php:77)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Applications/MAMP/htdocs/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/Exception.php:28)\n[previous exception] [object] (PDOException(code: 7): SQLSTATE[08006] [7] connection to server at \"127.0.0.1\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections? at /Applications/MAMP/htdocs/TEST_SYMFONY/vendor/doctrine/dbal/src/Driver/PDO/PgSQL/Driver.php:28)"} []
[2023-02-02T13:31:22.217231+00:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"adc3d7"},"request_uri":"http://127.0.0.1:8000/_wdt/adc3d7","method":"GET"} []
